# Generated by Django 6.1.1 on 2026-09-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('user', models.CharField(default='admin', max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=3, unique=True)),
                ('trading_economics_slug', models.CharField(blank=True, max_length=100)),
                ('yfinance_equity_ticker', models.CharField(blank=True, max_length=20)),
                ('imf_country_code', models.CharField(blank=True, max_length=10)),
                ('oecd_country_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('W', 'Weekly')], default='M', max_length=1)),
                ('default_source', models.CharField(choices=[('TE', 'TradingEconomics (WARI Scraper)'), ('IMF', 'IMF SDMX API'), ('OECD', 'OECD SDMX API'), ('YF', 'yfinance'), ('MAN', 'Manual Entry')], max_length=5)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FXPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_pairs', to='macro.country')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_pairs', to='macro.country')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Differential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(db_index=True)),
                ('base_value', models.FloatField(blank=True, null=True)),
                ('quote_value', models.FloatField(blank=True, null=True)),
                ('difference', models.FloatField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='True only when both base and quote values are available.')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentials', to='macro.fxpair')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentials', to='macro.macroindicator')),
            ],
            options={
                'ordering': ['pair', 'indicator', 'month'],
                'unique_together': {('pair', 'indicator', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(default='admin', max_length=100)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='macro.macroindicator')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('indicator', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='RatingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_diff', models.FloatField(blank=True, null=True)),
                ('max_diff', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_rules', to='macro.macroindicator')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='macro.ruleversion')),
            ],
            options={
                'ordering': ['indicator', 'min_diff'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('differential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='macro.differential')),
                ('applied_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_ratings', to='macro.ratingrule')),
                ('rule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='macro.ruleversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(db_index=True)),
                ('total_rating', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('bias', models.CharField(blank=True, choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('NEUTRAL', 'NEUTRAL')], max_length=10, null=True)),
                ('n_indicators', models.PositiveSmallIntegerField(default=0)),
                ('n_complete', models.PositiveSmallIntegerField(default=0, help_text='How many indicators had complete differentials.')),
                ('is_complete', models.BooleanField(default=False, help_text='True only when all active indicators have complete differentials.')),
                ('rule_version_snapshot', models.JSONField(default=dict, help_text='Snapshot of rule version numbers used at calculation time.')),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='macro.fxpair')),
            ],
            options={
                'ordering': ['pair', 'month'],
                'unique_together': {('pair', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MacroDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('manual', 'Manual Override'), ('revised', 'Revised'), ('missing', 'Missing')], default='published', max_length=20)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active_value', models.BooleanField(default=True, help_text='False when a newer published value has superseded this manual entry.')),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_points', to='macro.country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_points', to='macro.macroindicator')),
            ],
            options={
                'ordering': ['country', 'indicator', 'month'],
                'unique_together': {('country', 'indicator', 'month', 'is_active_value')},
            },
        ),
    ]
