# Generated by Django 6.1.1 on 2026-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
